name: CI

on: { push: { branches-ignore: wip/** } }

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with: { go-version: 1.26.0 }

      - name: Install windres
        run: |
            sudo apt-get install -y binutils-mingw-w64-x86-64
            sudo ln -s /usr/bin/x86_64-w64-mingw32-windres /usr/local/bin/windres

      - name: Build
        run:  go run tasks.go --build